### ISSUE TITLE
typedefed xml descs

### ISSUE THREAD

**Issue by async-cl** [haxetink/tink_xml#2]
Hi Juraj,

To keep it simple, this works for me, 

    @:list('content') var content:Array<{
        @:attr var id:String;
        @:attr var level:Int;
        @:attr var name:String;
        @:attr var description:String;
        @:list('topic') var topics:Array<{
            @:attr var level:Int;
            @:attr var id:String;
            @:attr var name:String;
            @:optional @:attr var path:String;
            @:attr var description:String;
            @:list('lesson') var lessons:Array<{
                @:attr var id:Int;
                @:attr var name:String;
                @:optional @:attr var path:String;
                @:optional @:attr var level:Int;
                @:optional @:attr var template:String;
                @:optional @:attr var visible:Bool;
            }>;
        }>;
    }>;

but this doesn't

```
typedef TLesson = {
    @:attr var id:Int;
    @:attr var name:String;
    @:optional @:attr var path:String;
    @:optional @:attr var level:Int;
    @:optional @:attr var template:String;
    @:optional @:attr var visible:Bool;
}

typedef TTopic = {
    @:attr var id:String;
    @:attr var path:String;
    @:optional @:attr var level:Int;
    @:optional @:attr var name:String;
    @:optional @:attr var description:String;
    @:list('lesson') var lessons:Array<TLesson>;
}

typedef TContent = {
    @:attr var id:String;
    @:optional @:attr var level:Int;
    @:optional @:attr var name:String;
    @:optional @:attr var description:String;
    @:list('topic') var topics:Array<TTopic>;
}

typedef TContentList = {
    @:list('content') var content:Array<TContent>;
}
```

should the typedefs work? I kind of want to reuse the typedefs to pick out parts of the structure.

Thanks!

**Comment by back2dos** [comment]
Closing this for now. Please get back to me if this is still an issue.
